channels:
  - conda-forge
  - pytorch
dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # User requirments
  - python=3.9
  - geopandas==0.9.0
  - numpy==1.23.4
  - plotly==4.14.3
  - PyYAML==6.0
  - tqdm==4.54.1
  - seaborn
  - zarr #added for ocean carbon analysis
  - pip
  - pip:
    - pandas==1.5.0
    - matplotlib==3.3.2
    - torch==1.11.0
    - scikit_learn==1.1.3
    - xarray==2022.10.0
    - learn2learn==0.1.7
    - fsspec #added for ocean carbon analysis
    - gcsfs  #added for ocean carbon analysis
